# Generated by Django 3.2.8 on 2021-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="config_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
