# Generated by Django 3.2.8 on 2021-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="schedule",
            field=models.JSONField(default=dict),
        ),
    ]
